services:
  project-manager-api:
    build: 
      context: product-manager-api
      dockerfile: Dockerfile
    volumes:
      - ./product-manager-api:/app
    ports:
      - 3000:3000
    env_file:
      - product-manager-api/.env
    command: npm run start:dev
    depends_on:
      - postgres
  
  postgres:
    build:
      context: db
      dockerfile: Dockerfile
    restart: always
    env_file:
      - product-manager-api/.env
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "levi@levi.com"
      PGADMIN_DEFAULT_PASSWORD: "levi"
    ports:
      - "16543:80"
    depends_on:
      - postgres
  # redis-stack:
  #     image: redis/redis-stack:latest
  #     container_name: redis-stack
  #     ports:
  #       - "6379:6379"
  #     volumes:
  #       - redis-stack-data:/data

volumes:
  postgres:
  # redis-stack-data: