services:
  project-manager-api:
    build: 
      context: product-manager-api
      dockerfile: Dockerfile
    volumes:
      - ./product-manager-api:/app
    ports:
      - 3000:3000
    env_file:
      - product-manager-api/.env
    command: npm run start:dev
    depends_on:
      - postgres
  
  postgres:
    image: postgres:13.5
    restart: always
    env_file:
      - product-manager-api/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: