FROM node:20.18-slim

RUN apt-get update -y && apt-get install -y openssl

USER node

RUN mkdir -p /home/node/app

WORKDIR /the/workdir/path

COPY --chown=node:node package*.json ./
RUN npm install

COPY --chown=node:node . .

RUN npx prisma generate

RUN npm run build

CMD ["npm", "run", "start:prod"]